package org.example.javasystematiskproject3restapi;

import jakarta.ws.rs.ApplicationPath;
import jakarta.ws.rs.core.Application;

@ApplicationPath("/api")
public class HelloApplication extends Application {

}

/*
 * It is just an autogenerated template that can be used for reference for our code.
 * This code defines a simple Jakarta EE application that sets up the base path  /api for RESTful APIs in the project.
 * It doesn’t contain any other functionality or logic because all the REST API implementations
 * are handled in other classes.
 */