package org.example.javasystematiskproject3restapi;

import jakarta.ws.rs.GET;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.Produces;

@Path("/hello-world")
public class HelloResource {
    @GET
    @Produces("text/plain")
    public String hello() {
        return "Hello, World!";
    }
}


/*
 * Like HelloApplication, this is also an autogenerated template that can be used for reference for our code while calling APIs
 */